=== ShayanBits/XMLDemo2/libraryScheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/libraryScheme"
	xmlns:tns="http://www.example.org/libraryScheme"
	elementFormDefault="qualified">

	<complexType name="libraryType">
		<sequence>
			<element name="book" type="tns:bookType" maxOccurs="unbounded">
			</element>
			<element name="author" type="tns:authorType" maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>

	<complexType name="bookType">
		<sequence>
			<element name="title" type="string"></element>
			<element name="language" type="tns:languageType"></element>
			<element name="year" type="tns:yearType"></element>
		</sequence>
	</complexType>

	<complexType name="authorType">
		<sequence>
			<element name="last-name" type="string"></element>
			<element name="first-name" type="string"></element>
		</sequence>
		<attribute name="id" type="ID" use="required"></attribute>
	</complexType>
	<simpleType name="yearType">
		<restriction base="integer">
		<pattern value="[1-3][0-9][0-9][0-9]"></pattern>
		</restriction> 
	</simpleType>
	<simpleType name="languageType">
		<restriction base="string">
		<pattern value="de|en|fr|fa|ar|[a-z][a-z]"></pattern>
		</restriction> 
	</simpleType>
	

	<element name="library" type="tns:libraryType" />
</schema>

=== ShayanBits/XMLDemo2/LibraryFromSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:library xmlns:tns="http://www.example.org/libraryScheme" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/libraryScheme libraryScheme.xsd ">
  <tns:book>
    <tns:title>Titel1</tns:title>
    <tns:language>de</tns:language>
    <tns:year>1500</tns:year>
  </tns:book>
  <tns:book>
    <tns:title>Einfuerung in Objektorientiert Programmierung</tns:title>
    <tns:language>fa</tns:language>
    <tns:year>1992</tns:year>
  </tns:book>
  <tns:book>
    <tns:title>JQuery</tns:title>
    <tns:language>en</tns:language>
    <tns:year>2000</tns:year>
  </tns:book>
  <tns:book>
    <tns:title>XML in nutshell </tns:title>
    <tns:language>fa</tns:language>
    <tns:year>2018</tns:year>
  </tns:book>
  <tns:author id="idvalue0">
    <tns:last-name>Sh</tns:last-name>
    <tns:first-name>Shayan</tns:first-name>
  </tns:author>
  <tns:author id="idvalue1">
    <tns:last-name>Mustermann</tns:last-name>
    <tns:first-name>Max</tns:first-name>
  </tns:author>
  <tns:author id="idvalue3">
    <tns:last-name>MMF</tns:last-name>
    <tns:first-name>Max</tns:first-name>
  </tns:author>
  
</tns:library>

=== ShayanBits/XMLDemo2/libraryFromScheme.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:library xmlns:tns="http://www.example.org/libraryScheme" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/libraryScheme libraryScheme.xsd ">
  <tns:book>
    <tns:author-ref>tns:author-ref</tns:author-ref>
    <tns:title>tns:title</tns:title>
    <tns:language>si</tns:language>
    <tns:year>1999</tns:year>
  </tns:book>
    <tns:book>
    <tns:author-ref>tns:author-ref1</tns:author-ref>
    <tns:title>tns:title</tns:title>
    <tns:language>de</tns:language>
    <tns:year>1920</tns:year>
  </tns:book>
    <tns:book>
    <tns:author-ref>tns:author-ref2</tns:author-ref>
    <tns:title>tns:title</tns:title>
    <tns:language>fr</tns:language>
    <tns:year>1500</tns:year>
  </tns:book>
  <tns:author id="idvalue0">
    <tns:last-name>tns:last-name</tns:last-name>
    <tns:first-name>tns:first-name</tns:first-name>
  </tns:author>
  <tns:author id="idvalue1">
    <tns:last-name>tns:last-name</tns:last-name>
    <tns:first-name>tns:first-name</tns:first-name>
  </tns:author>
</tns:library>
