=== ShayanBits/XMLDemo2/XMLType.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!ELEMENT XMLFile (header,header2)>
<!ELEMENT header (title+)>
<!ELEMENT header2 (car+)>
<!ELEMENT title (subtitle)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT car (#PCDATA)>
<!ATTLIST title tid ID #REQUIRED>
<!ATTLIST car carID ID #REQUIRED> 
<!ATTLIST car model (AUDI|BMW|BENZ|SEAT) "SEAT">

=== ShayanBits/XMLDemo2/XMLsandbox.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE XMLFile SYSTEM "XMLType.dtd"> 
<XMLFile>
	<header>
		<title tid="t1">
			<subtitle>and a subtitle</subtitle>
		</title>
		<title tid="t2">
			<subtitle>and a subtitle</subtitle>
		</title>
	</header>
	<header2>
		<car carID="c1" >test</car>
		<car carID="c2"  model="AUDI">test</car>
	</header2>
</XMLFile>
